### PR TITLE
add AMD wrapper

### PR DESCRIPTION
**Pull request by shmax**
Adding hooks for AMD/Commonjs folks. Everyone else will remain unaffected.

### CODE REVIEW

**Comment by AlexDpy** [comment]
Thank you @shmax  :+1:

**Comment by shmax** [comment]
My pleasure. Don't forget to bump the release version!

**Comment by shmax** [comment]
1.0.1 is still marked as the "Latest release"...

**Comment by AlexDpy** [comment]
Sorry, it should work now.

**Comment by shmax** [comment]
Beautiful, we're all set! Thanks much for the great widget.

**Pull request merged**
